version: '3.9'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    command: yarn start
    volumes:
      - ./dist:/usr/app/dist/
      - ./package.json:/usr/app/package.json
    image: clean-code
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - "mongo"
    depends_on:
      - mongo