version: '3.9'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16.15-alpine
    working_dir: /usr/app/
    restart: always
    command: [yarn, docker:run]
    volumes:
      - ./dist/:/usr/app/dist/
      - ./package.json:/usr/app/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - "mongo"
    depends_on:
      - mongo